# -*- coding: utf-8 -*-
"""svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SEr94eLAbqlIHOs1UlliFtJHf7x5Zp66
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.svm import NuSVC
from sklearn.metrics import accuracy_score
import random
import warnings

warnings.filterwarnings("ignore")

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/letter-recognition/letter-recognition.data"

columns = [
    "letter", "x-box", "y-box", "width", "high", "onpix", "x-bar",
    "y-bar", "x2bar", "y2bar", "xybar", "x2ybr", "xy2br", "x-ege",
    "xegvy", "y-ege", "yegvx"
]

df = pd.read_csv(url, header=None, names=columns)
print("Original dataset shape:", df.shape)
df.head()

print("\nInfo:")
print(df.info())

print("\nClass distribution (first 10):")
print(df["letter"].value_counts().head(10))

print("\nDescribe:")
display(df.describe())

X_full = df.drop("letter", axis=1).values
y_full = df["letter"].values

n_rows_to_use = 6000    # you can increase (e.g. 8000) if Colab is fast enough

sss = StratifiedShuffleSplit(
    n_splits=1, train_size=n_rows_to_use, random_state=RANDOM_SEED
)
for idx, _ in sss.split(X_full, y_full):
    X = X_full[idx]
    y = y_full[idx]

print("Sub-sampled dataset shape:", X.shape)

# Standardization
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# =========================
# 5. Optimization function for NuSVM
# =========================
def optimize_svm_for_split(X_train, X_test, y_train, y_test,
                           n_iterations=100):
    kernels = ["linear", "rbf", "poly", "sigmoid"]

    best_accuracy = 0.0
    best_params = None
    best_acc_history = []

    for it in range(1, n_iterations + 1):
        kernel = random.choice(kernels)
        nu = np.random.uniform(0.1, 0.9)              # (0,1]
        epsilon = 10 ** np.random.uniform(-4, -1)     # 1e-4 to 1e-1 (used as tol)

        model = NuSVC(kernel=kernel, nu=nu, tol=epsilon, gamma="scale")
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred) * 100.0

        if acc > best_accuracy:
            best_accuracy = acc
            best_params = {"kernel": kernel, "nu": nu, "epsilon": epsilon}

        best_acc_history.append(best_accuracy)

        # small progress every 20 iterations so you see it's alive
        if it % 20 == 0:
            print(f"    Iter {it:3d} | current acc={acc:.2f}% | best={best_accuracy:.2f}%")

    return best_accuracy, best_params, best_acc_history

# =========================
# 6. Run optimization for 10 samples (S1–S10)
# =========================
n_samples = 10
test_size = 0.30
n_iterations = 100  # requirement of the question

results = []
histories = []

for s in range(1, n_samples + 1):
    print(f"\n=== Optimizing Sample S{s} ===")

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=test_size, stratify=y,
        random_state=RANDOM_SEED + s
    )

    best_acc, best_params, history = optimize_svm_for_split(
        X_train, X_test, y_train, y_test,
        n_iterations=n_iterations
    )

    results.append({
        "Sample": f"S{s}",
        "Best Accuracy (%)": best_acc,
        "Best Kernel": best_params["kernel"],
        "Best Nu": best_params["nu"],
        "Best Epsilon": best_params["epsilon"]
    })
    histories.append(history)

    print(f"--> S{s} best accuracy: {best_acc:.2f}%")
    print(f"    best params: {best_params}")

table_df = pd.DataFrame(results)
table_df["Best Accuracy (%)"] = table_df["Best Accuracy (%)"].round(2)
table_df["Best Nu"] = table_df["Best Nu"].round(4)
table_df["Best Epsilon"] = table_df["Best Epsilon"].map(lambda x: "{:.4e}".format(x))

print("\nTable 1: Comparative performance of Optimized-SVM with different samples")
display(table_df)

# =========================
# 8. Convergence graph of best SVM (Figure 1)
# =========================
best_idx = table_df["Best Accuracy (%)"].astype(float).idxmax()
best_sample = table_df.loc[best_idx, "Sample"]
best_history = histories[best_idx]

print(f"Best sample: {best_sample}")
display(table_df.loc[[best_idx]])

plt.figure(figsize=(8,5))
plt.plot(range(1, len(best_history)+1), best_history)
plt.xlabel("Iteration")
plt.ylabel("Accuracy (%)")
plt.title(f"Fitness (bestAccuracy) - {best_sample}")
plt.grid(True)
plt.show()

# =========================
# 9. Save results for GitHub (optional)
# =========================
table_df.to_csv("optimized_svm_results_letter_subset.csv", index=False)

best_hist_df = pd.DataFrame({
    "Iteration": np.arange(1, len(best_history)+1),
    "BestAccuracy": best_history
})
best_hist_df.to_csv("best_sample_convergence_subset.csv", index=False)

print("Saved:")
print("- optimized_svm_results_letter_subset.csv")
print("- best_sample_convergence_subset.csv")

